version: '3'
services:
  app-client:
    image: users-client
    build: ../user-microservice-ui
    ports:
      - '3000:3000'
  app-server:
    image: users-server
    build: .
    ports:
      - '8082:8123'

